migrate-up:
	migrate - path ./infra/databasemigration -database "postgres://postgres:password@localhost:5432/test?sslmode=disable" -verbose up

migrate-down:
	migrate - path ./infra/databasemigration -database "postgres://postgres:password@localhost:5432/test?sslmode=disable" -verbose down