// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ItESOmUGjw3wXzrE30dYhjQJDobHnxQ',
    appId: '1:1062336289419:web:7a157ee9dbe323e770928e',
    messagingSenderId: '1062336289419',
    projectId: 'event-app-748e5',
    authDomain: 'event-app-748e5.firebaseapp.com',
    storageBucket: 'event-app-748e5.appspot.com',
    measurementId: 'G-RXH6ZVJPDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb6kWuf-OGcQYDxj4Sj7lZZh4Goh0QtPQ',
    appId: '1:1062336289419:android:6d87a478fab48aaf70928e',
    messagingSenderId: '1062336289419',
    projectId: 'event-app-748e5',
    storageBucket: 'event-app-748e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPJeGw1f-hg-dx7hRLUj4C4S17ttmCvuI',
    appId: '1:1062336289419:ios:212f5b8727f4e74770928e',
    messagingSenderId: '1062336289419',
    projectId: 'event-app-748e5',
    storageBucket: 'event-app-748e5.appspot.com',
    iosClientId: '1062336289419-4ksju4o7m50dbnousavb67b5otnidaj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventMate',
  );
}
